### ISSUE TITLE
ModuleNotFoundError exception when IPython in not installed

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#1241]
```
python ~/bad.py (this is the script posted above)
Traceback (most recent call last):
  File "/Users/pwessel/bad.py", line 2, in <module>
    import pygmt
  File "/Users/pwessel/GMTdev/pygmt/pygmt/__init__.py", line 28, in <module>
    from pygmt.figure import Figure, set_display
  File "/Users/pwessel/GMTdev/pygmt/pygmt/figure.py", line 9, in <module>
    import IPython
ModuleNotFoundError: No module named 'IPython'
```

_Originally posted by @PaulWessel in https://github.com/GenericMappingTools/pygmt/issues/732#issuecomment-827182631_

**Comment by seisman** [comment]
https://github.com/GenericMappingTools/pygmt/blob/7466dc31f3cbdc15c730c4fcfe430a73d44a2808/pygmt/figure.py#L8-L11

When IPython is not installed, it raises a `ModuleNotFoundError` exception, but the code incorrectly checks the `KeyError` exception. 

We should fix it and ideally add a test.
