### ISSUE TITLE
Remote download is deactivated, unable to obtain remote file for earth relief

### ISSUE THREAD

**Issue by darren-tpk** [GenericMappingTools/pygmt#1556]
**Description of the problem**

load_earth_relief() is not working as intended, due to an error with grdcut mentioning that "remote download is currently deactivated". When trying to resolve this issue myself, I was looking into the deprecated GMT_AUTO_DOWNLOAD setting, but my attempts at changing GMT_DATA_UPDATE_INTERVAL does not resolve anything. While the full code I provided below is my own, the examples from the load_earth_relief documentation produce the same error as well. 

**Full code that generated the error**

```python
import pygmt
region = [-119.25, -118.95, 37.525, 37.725]
grid = pygmt.datasets.load_earth_relief(resolution="01s", region=region)
```

**Full error message**

```
grdcut [ERROR]: Remote download is currently deactivated
grdcut [ERROR]: Unable to obtain remote file @earth_relief_01s
Traceback (most recent call last):
  File "/opt/miniconda3/envs/enhance_catalog/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-b9311e363d7b>", line 3, in <module>
    grid = pygmt.datasets.load_earth_relief(resolution="01s", region=region)
  File "/opt/miniconda3/envs/enhance_catalog/lib/python3.8/site-packages/pygmt/helpers/decorators.py", line 725, in new_module
    return module_func(*args, **kwargs)
  File "/opt/miniconda3/envs/enhance_catalog/lib/python3.8/site-packages/pygmt/datasets/earth_relief.py", line 140, in load_earth_relief
    grid = grdcut(f"@{earth_relief_prefix}{resolution}{reg}", region=region)
  File "/opt/miniconda3/envs/enhance_catalog/lib/python3.8/site-packages/pygmt/helpers/decorators.py", line 582, in new_module
    return module_func(*args, **kwargs)
  File "/opt/miniconda3/envs/enhance_catalog/lib/python3.8/site-packages/pygmt/helpers/decorators.py", line 725, in new_module
    return module_func(*args, **kwargs)
  File "/opt/miniconda3/envs/enhance_catalog/lib/python3.8/site-packages/pygmt/src/grdcut.py", line 99, in grdcut
    lib.call_module("grdcut", arg_str)
  File "/opt/miniconda3/envs/enhance_catalog/lib/python3.8/site-packages/pygmt/clib/session.py", line 505, in call_module
    raise GMTCLibError(
pygmt.exceptions.GMTCLibError: Module 'grdcut' failed with status code 72:
grdcut [ERROR]: Remote download is currently deactivated
grdcut [ERROR]: Unable to obtain remote file @earth_relief_01s
```

**System information**

Please paste the output of `python -c "import pygmt; pygmt.show_versions()"`:

```
PyGMT information:
  version: v0.4.1
System information:
  python: 3.8.12 | packaged by conda-forge | (default, Sep 29 2021, 19:44:33)  [Clang 11.1.0 ]
  executable: /opt/miniconda3/envs/enhance_catalog/bin/python
  machine: macOS-10.16-x86_64-i386-64bit
Dependency information:
  numpy: 1.21.2
  pandas: 1.3.2
  xarray: 0.19.0
  netCDF4: 1.5.7
  packaging: 21.0
  ghostscript: 9.54.0
  gmt: 6.2.0
GMT library information:
  binary dir: /opt/miniconda3/envs/enhance_catalog/bin
  cores: 8
  grid layout: rows
  library path: /opt/miniconda3/envs/enhance_catalog/lib/libgmt.dylib
  padding: 2
  plugin dir: /opt/miniconda3/envs/enhance_catalog/lib/gmt/plugins
  share dir: /opt/miniconda3/envs/enhance_catalog/share/gmt
  version: 6.2.0
```

**Comment by meghanrjones** [comment]
We are experiencing an issue with the GMT server. In the meantime, you can use `pygmt.config(GMT_DATA_SERVER="https://oceania.generic-mapping-tools.org")` to get your code to work:

```
import pygmt
region = [-119.25, -118.95, 37.525, 37.725]
pygmt.config(GMT_DATA_SERVER="https://oceania.generic-mapping-tools.org")
grid = pygmt.datasets.load_earth_relief(resolution="01s", region=region)
```

**Comment by weiji14** [comment]
Hi @darren-uaf, there are some issues with the GMT server currently, see https://github.com/GenericMappingTools/gmt/issues/5830. The current workaround would be to set the [`GMT_DATA_URL`](https://docs.generic-mapping-tools.org/6.2/gmt.conf.html#term-GMT_DATA_SERVER) to use https like so:

```python
with pygmt.config("GMT_DATA_SERVER"="https://oceania.generic-mapping-tools.org"):
    grid = pygmt.datasets.load_earth_relief(resolution="01s", region=region)
```

Or you can choose one of the other "Data Server Mirrors" at https://www.generic-mapping-tools.org/mirrors/. Let us know if it works.

**Comment by darren-tpk** [comment]
@meghanrjones @weiji14 Thank you for your prompt responses. Sorry that I missed the other open issue, it didn't come up when I searched load_earth_relief(). Your suggestions fixed this issue, thanks!

**Comment by meghanrjones** [comment]
The server issue has been fixed by RCF staff, so you can try re-running your script without the pygmt.config() setting. Please post if you run into any more issues.
