### ISSUE TITLE
Error loading GMT shared library at 'libgmt.dylib'

### ISSUE THREAD

**Issue by jlmaurer** [GenericMappingTools/pygmt#1923]
**Description of the problem**

Problem with one of the GMT libraries on a fresh install of pygmt in a new conda env. 

```python
conda create --name pygmt_test
conda activate pygmt_test
mamba install --channel conda-forge pygmt
python
import pygmt
```

**Full error message**

```
>>> import pygmt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jeremym/miniconda3/envs/pygmt_test/lib/python3.10/site-packages/pygmt/__init__.py", line 71, in <module>
    _begin()
  File "/Users/jeremym/miniconda3/envs/pygmt_test/lib/python3.10/site-packages/pygmt/session_management.py", line 16, in begin
    with Session() as lib:
  File "/Users/jeremym/miniconda3/envs/pygmt_test/lib/python3.10/site-packages/pygmt/clib/session.py", line 183, in __enter__
    self.create("pygmt-session")
  File "/Users/jeremym/miniconda3/envs/pygmt_test/lib/python3.10/site-packages/pygmt/clib/session.py", line 330, in create
    c_create_session = self.get_libgmt_func(
  File "/Users/jeremym/miniconda3/envs/pygmt_test/lib/python3.10/site-packages/pygmt/clib/session.py", line 282, in get_libgmt_func
    self._libgmt = load_libgmt()
  File "/Users/jeremym/miniconda3/envs/pygmt_test/lib/python3.10/site-packages/pygmt/clib/loading.py", line 59, in load_libgmt
    raise GMTCLibNotFoundError("\n".join(error_msg))
pygmt.exceptions.GMTCLibNotFoundError: Error loading GMT shared library at '/Users/jeremym/miniconda3/envs/pygmt_test/lib/libgmt.dylib'.
dlopen(/Users/jeremym/miniconda3/envs/pygmt_test/lib/libgmt.dylib, 0x0006): Symbol not found: _ZSTD_compressBound
  Referenced from: /Users/jeremym/miniconda3/envs/pygmt_test/lib/libgdal.30.dylib
  Expected in: /Users/jeremym/miniconda3/envs/pygmt_test/lib/libblosc.1.21.1.dylib
Error loading GMT shared library at 'libgmt.dylib'.
dlopen(libgmt.dylib, 0x0006): Symbol not found: _ZSTD_compressBound
  Referenced from: /Users/jeremym/miniconda3/envs/pygmt_test/lib/libgdal.30.dylib
  Expected in: /Users/jeremym/miniconda3/envs/pygmt_test/lib/libblosc.1.21.1.dylib
```

**System information**
This command: `python -c "import pygmt; pygmt.show_versions()"` doesn't work due to the above error. `sys.version_info` gives the following:
```
sys.version_info(major=3, minor=10, micro=4, releaselevel='final', serial=0)
```
and platform.platform() gives: 
```
'macOS-12.3.1-x86_64-i386-64bit'
```

**Comment by weiji14** [comment]
Hi @jlmaurer, thanks for the bug report. We're aware of the issue, and it seems to be a problem on conda-forge due to `blosc` (which `gdal` depends on) no longer packaging ZSTD, see https://github.com/conda-forge/blosc-feedstock/pull/53#issuecomment-1122080567. Hopefully this will get sorted out in the next day or so.

**Comment by weiji14** [comment]
As a workaround, could you try `mamba install --channel conda-forge pygmt blosc=1.21.0` and see if it works? Sorry that I can't test this, don't have a mac with me.

**Comment by jlmaurer** [comment]
@weiji14 that did the trick! Thanks

**Comment by seisman** [comment]
The macOS CI works again. I think the upstream issue has been fixed.
