### ISSUE TITLE
Compatibility with PySide6 QApplication() in Linux

### ISSUE THREAD

**Issue by xwanner** [GenericMappingTools/pygmt#3172]
### Description of the problem

I am writing an app with a UI made with PySide6 (i.e. Qt). The base command to generate the app is `app = QApplication()`

I cannot generate any figure when pygmt is ran after a QApplication() command.

PySide6 is installed via pip (I cannot install it via conda since the conda package is lacking some modules).

I don't have the issue in windows.

### Minimal Complete Verifiable Example

```python
This work :

from PySide6.QtWidgets import QApplication

import pygmt
fig = pygmt.Figure()
fig.coast(region=[-180, 180, -90, 90], shorelines=True, frame=True)
fig.show()

app = QApplication()


And this does not :

from PySide6.QtWidgets import QApplication

app = QApplication()

import pygmt
fig = pygmt.Figure()
fig.coast(region=[-180, 180, -90, 90], shorelines=True, frame=True)
fig.show()
```

### Full error message

```python-traceback
Error: /undefined in 0,06
Operand stack:
Execution stack:   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   1933   1   3   %oparray_pop   1932   1   3   %oparray_pop   1917   1   3   %oparray_pop   1787   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--
Dictionary stack:   --dict:752/1123(ro)(G)--   --dict:0/20(G)--   --dict:85/200(L)--   --dict:150/250(L)--
Current allocation mode is local
Last OS error: No such file or directoryCurrent file position is 20867
psconvert [ERROR]: System call [gs -q -dNOSAFER -dNOPAUSE -dBATCH -sDEVICE=bbox -DPSL_no_pagefill -dMaxBitmap=2147483647 -dUseFastColor=true '/home/xwanner/.gmt/sessions/gmt_session.67849/gmt_1.ps-' 2> '/home/xwanner/.gmt/sessions/gmt_session.67849/psconvert_67849c.bb'] returned error 256.
Traceback (most recent call last):
  File "/home/xwanner/Documents/FUGRO/GravPro_FlightAnalyst/gravpro-ng/src/debug/test.py", line 10, in <module>
    fig.show()
  File "/home/xwanner/miniforge3/envs/gravpro-ng/lib/python3.11/site-packages/pygmt/figure.py", line 468, in show
    pdf = self._preview(
          ^^^^^^^^^^^^^^
  File "/home/xwanner/miniforge3/envs/gravpro-ng/lib/python3.11/site-packages/pygmt/figure.py", line 495, in _preview
    self.savefig(fname, dpi=dpi, **kwargs)
  File "/home/xwanner/miniforge3/envs/gravpro-ng/lib/python3.11/site-packages/pygmt/figure.py", line 374, in savefig
    self.psconvert(prefix=prefix, fmt=fmt, crop=crop, **kwargs)
  File "/home/xwanner/miniforge3/envs/gravpro-ng/lib/python3.11/site-packages/pygmt/helpers/decorators.py", line 603, in new_module
    return module_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xwanner/miniforge3/envs/gravpro-ng/lib/python3.11/site-packages/pygmt/helpers/decorators.py", line 776, in new_module
    return module_func(*bound.args, **bound.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xwanner/miniforge3/envs/gravpro-ng/lib/python3.11/site-packages/pygmt/figure.py", line 252, in psconvert
    lib.call_module(
  File "/home/xwanner/miniforge3/envs/gravpro-ng/lib/python3.11/site-packages/pygmt/clib/session.py", line 624, in call_module
    raise GMTCLibError(
pygmt.exceptions.GMTCLibError: Module 'psconvert' failed with status code 79:
psconvert [ERROR]: System call [gs -q -dNOSAFER -dNOPAUSE -dBATCH -sDEVICE=bbox -DPSL_no_pagefill -dMaxBitmap=2147483647 -dUseFastColor=true '/home/xwanner/.gmt/sessions/gmt_session.67849/gmt_1.ps-' 2> '/home/xwanner/.gmt/sessions/gmt_session.67849/psconvert_67849c.bb'] returned error 256.
```

### System information

```bash
PyGMT information:
  version: v0.11.0
System information:
  python: 3.11.8 | packaged by conda-forge | (main, Feb 16 2024, 20:53:32) [GCC 12.3.0]
  executable: /home/xwanner/miniforge3/envs/gravpro-ng/bin/python
  machine: Linux-5.15.0-101-generic-x86_64-with-glibc2.35
Dependency information:
  numpy: 1.26.4
  pandas: 2.2.2
  xarray: 2024.3.0
  netCDF4: 1.6.5
  packaging: 24.0
  contextily: None
  geopandas: 0.14.3
  ipython: None
  rioxarray: None
  ghostscript: 10.03.0
GMT library information:
  binary version: 6.5.0
  cores: 8
  grid layout: rows
  image layout: 
  library path: /home/xwanner/miniforge3/envs/gravpro-ng/lib/libgmt.so
  padding: 2
  plugin dir: /home/xwanner/miniforge3/envs/gravpro-ng/lib/gmt/plugins
  share dir: /home/xwanner/miniforge3/envs/gravpro-ng/share/gmt
  version: 6.5.0
```

**Comment by seisman** [comment]
Your two scripts work well for me on Linux, but I installed PySide6 using conda, not pip.

**Comment by xwanner** [comment]
Yes, I think the problem is with PySide6 installed from pip. I will try to post an isssue on the pyside git repo.

**Comment by seisman** [comment]
I don't use PySide6, so I'm not sure, but following command fails, so I guess the answer is no.
```
>>> from PySide6.QtWebEngineWidgets import QWebEngineView
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'PySide6.QtWebEngineWidgets'
```

**Comment by seisman** [comment]
As mentioned above, I've never used PySide6 and I also don't understand why PySide6 would make PyGMT fail. I may provide more help if you can upload the file  `/home/xwanner/.gmt/sessions/gmt_session.67849/gmt_1.ps-` to GitHub.

**Comment by xwanner** [comment]
[gmt_1.zip](https://github.com/GenericMappingTools/pygmt/files/14978296/gmt_1.zip)

Here is the file.
But I am pretty sure since you tested it, that the problem comes from a local vs. global path conflict between conda and pip.

**Comment by seisman** [comment]
In your script, I see the following line which cause troubles:
```
%%BeginPageSetup
V 0,06 0,06 scale
%%EndPageSetup
```
It should be `V 0.06 0.06 scale` instead. So it must be something "wrong" with the [decimal separator](https://en.wikipedia.org/wiki/Decimal_separator).

**Comment by seisman** [comment]
I believe it's caused by the change in the system's **LC** settings, and there is nothing we can do on the PyGMT side. Closing the issue.
