### ISSUE TITLE
Error loading GMT shared library at 'gmt.dll'.

### ISSUE THREAD

**Issue by kjz1997** [GenericMappingTools/pygmt#3339]
### Description of the problem

I install the pygmt by conda
When it was first installed a few months ago, it could be used, but this error suddenly occurred a while ago. I have followed the steps to set the environment variables on the GMT forum, but it still reports an error
![image](https://github.com/user-attachments/assets/843b030b-1516-4641-aac1-4daaffc22bb5)

### Minimal Complete Verifiable Example

```python
import pygmt


# Load sample earth relief data
grid = pygmt.datasets.load_earth_relief(resolution="10m", region=[109, 117.4, 20, 25.6])
fig = pygmt.Figure()
fig.grdview(
    grid=grid,
    # Set the azimuth to -130 (230) degrees and the elevation to 30 degrees
    perspective=[-130, 30],
    frame=["xaf", "yaf", "WSnE"],
    projection="M15c",
    zsize="1.5c",
    surftype="s",
    cmap="geo",
    plane="1000+ggrey",
    # Set the contour pen thickness to "0.1p"
    contourpen="0.1p",
)
fig.colorbar(perspective=True, frame=["a500", "x+lElevation", "y+lm"])
fig.show()
```

### Full error message

```python-traceback
Traceback (most recent call last):
  File "d:\python\PyFile\gmt\gmtmath.py", line 1, in <module>
    import pygmt
  File "C:\Users\kjzha\.conda\envs\pygmt\Lib\site-packages\pygmt\__init__.py", line 29, in <module>
    with clib.Session() as lib:
  File "C:\Users\kjzha\.conda\envs\pygmt\Lib\site-packages\pygmt\clib\session.py", line 217, in __enter__        
    self.create("pygmt-session")
  File "C:\Users\kjzha\.conda\envs\pygmt\Lib\site-packages\pygmt\clib\session.py", line 364, in create
    c_create_session = self.get_libgmt_func(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kjzha\.conda\envs\pygmt\Lib\site-packages\pygmt\clib\session.py", line 316, in get_libgmt_func  
    self._libgmt = load_libgmt()
                   ^^^^^^^^^^^^^
  File "C:\Users\kjzha\.conda\envs\pygmt\Lib\site-packages\pygmt\clib\loading.py", line 60, in load_libgmt       
    raise GMTCLibNotFoundError("\n".join(error_msg))
pygmt.exceptions.GMTCLibNotFoundError: Error loading GMT shared library at 'C:\Users\kjzha\.conda\envs\pygmt\Library\bin\gmt.dll'.
Could not find module 'C:\Users\kjzha\.conda\envs\pygmt\Library\bin\gmt.dll' (or one of its dependencies). Try using the full path with constructor syntax.
Error loading GMT shared library at 'gmt.dll'.
Could not find module 'gmt.dll' (or one of its dependencies). Try using the full path with constructor syntax.   
Error loading GMT shared library at 'gmt_w64.dll'.
Could not find module 'gmt_w64.dll' (or one of its dependencies). Try using the full path with constructor syntax.    
Error loading GMT shared library at 'gmt_w32.dll'.
Could not find module 'gmt_w32.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

### System information

```bash
Traceback (most recent call last):
  File "d:\python\PyFile\gmt\gmtmath.py", line 1, in <module>
    import pygmt
  File "C:\Users\kjzha\.conda\envs\pygmt\Lib\site-packages\pygmt\__init__.py", line 29, in <module>
    with clib.Session() as lib:
  File "C:\Users\kjzha\.conda\envs\pygmt\Lib\site-packages\pygmt\clib\session.py", line 217, in __enter__        
    self.create("pygmt-session")
  File "C:\Users\kjzha\.conda\envs\pygmt\Lib\site-packages\pygmt\clib\session.py", line 364, in create
    c_create_session = self.get_libgmt_func(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kjzha\.conda\envs\pygmt\Lib\site-packages\pygmt\clib\session.py", line 316, in get_libgmt_func  
    self._libgmt = load_libgmt()
                   ^^^^^^^^^^^^^
  File "C:\Users\kjzha\.conda\envs\pygmt\Lib\site-packages\pygmt\clib\loading.py", line 60, in load_libgmt       
    raise GMTCLibNotFoundError("\n".join(error_msg))
pygmt.exceptions.GMTCLibNotFoundError: Error loading GMT shared library at 'C:\Users\kjzha\.conda\envs\pygmt\Library\bin\gmt.dll'.
Could not find module 'C:\Users\kjzha\.conda\envs\pygmt\Library\bin\gmt.dll' (or one of its dependencies). Try using the full path with constructor syntax.
Error loading GMT shared library at 'gmt.dll'.
Could not find module 'gmt.dll' (or one of its dependencies). Try using the full path with constructor syntax.   
Error loading GMT shared library at 'gmt_w64.dll'.
Could not find module 'gmt_w64.dll' (or one of its dependencies). Try using the full path with constructor syntax.    
Error loading GMT shared library at 'gmt_w32.dll'.
Could not find module 'gmt_w32.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

**Comment by seisman** [comment]
Please try to remove the current `pygmt` environment and create a new one following the install instructions.

**Comment by seisman** [comment]
No responses. Closing the issue.
