### ISSUE TITLE
"Error \undefined in nan" when using log scale for colormap

### ISSUE THREAD

**Issue by paradx** [GenericMappingTools/pygmt#3681]
### Description of the problem

When trying to plot a dataset with colored dots on a log scale I get an error from psconvert. 

The plot on a linear scale works fine:
![tau_plot](https://github.com/user-attachments/assets/243d5fa7-e056-4d45-9614-de5d3bc846e1)

I'd expect to just have a changed color bar and adjusted colors on the plot

### Minimal Complete Verifiable Example

```python
import pygmt
from pathlib import Path

# Load example data (see below)
data = "./example_data.txt"  # Replace with your file path
# Start a figure
fig = pygmt.Figure()

# Define region and projection (using a polar coord of the arctic region
fig.coast(projection="S0/90/30c", region=[0,360,60,90], frame=["ag","+tMWE"], land="tan", lakes="azure", water="lightblue",shorelines="1/0.5p")

# Make color palette THIS FAILS WITH log=True
pygmt.makecpt(cmap="hot", series=[0, 6000], log=True)

# Plot the points
fig.plot(data=data, style="c0.05c", fill="+z", cmap=True)

# Add a colorbar
fig.colorbar(frame='af+l"Tau"')

fig.savefig("tau_plot.png")

# for generating the test data: 
import pandas as pd
import numpy as np

data = {
        "lon": np.linspace(-60,68,num=20000) + np.random.randint(-10,10,size=20000)/10, 
        "lat": np.linspace(50,90,num=20000) + np.random.randint(0,70,size=20000)/10,
        "tau": np.sin(np.random.randint(0,31,size=20000)/10)*np.linspace(0,4000,num=20000)+np.random.randint(0,50,size=20000),
        }

# Convert data to a pandas DataFrame
df = pd.DataFrame(data)
file_name = "example_data.txt"
df.to_csv(file_name, sep="\t", index=False, header=False)
```

### Full error message

```python-traceback
Error: /undefined in nan
Operand stack:

Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   1933   1   3   %oparray_pop   1932   1   3   %oparray_pop   1917   1   3   %oparray_pop   1787   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   --nostringval--
Dictionary stack:
   --dict:753/1123(ro)(G)--   --dict:0/20(G)--   --dict:85/200(L)--   --dict:159/250(L)--
Current allocation mode is local
Last OS error: No such file or directory
Current file position is 2521655
psconvert [ERROR]: System call [gs -q -dNOSAFER -dNOPAUSE -dBATCH -sDEVICE=bbox -DPSL_no_pagefill -dMaxBitmap=2147483647 -dUseFastColor=true '/home/landrae/.gmt/sessions/gmt_session.680420/gmt_1.ps-' 2> '/home/landrae/.gmt/sessions/gmt_session.680420/psconvert_680420c.bb'] returned error 256.
Traceback (most recent call last):
  File "/home/landrae/Dokumente/W01/10-19 PHD/14_Software/14.11 Aerosnow/tests/plottygmt.py", line 24, in <module>
    fig.savefig("tau_plot.png")
  File "/nix/store/9hyjjdx8swcs87j75x86fiqakswnvsam-python3-3.11.10-env/lib/python3.11/site-packages/pygmt/figure.py", line 374, in savefig
    self.psconvert(prefix=prefix, fmt=fmt, crop=crop, **kwargs)
  File "/nix/store/9hyjjdx8swcs87j75x86fiqakswnvsam-python3-3.11.10-env/lib/python3.11/site-packages/pygmt/helpers/decorators.py", line 603, in new_module
    return module_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/9hyjjdx8swcs87j75x86fiqakswnvsam-python3-3.11.10-env/lib/python3.11/site-packages/pygmt/helpers/decorators.py", line 776, in new_module
    return module_func(*bound.args, **bound.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/9hyjjdx8swcs87j75x86fiqakswnvsam-python3-3.11.10-env/lib/python3.11/site-packages/pygmt/figure.py", line 252, in psconvert
    lib.call_module(
  File "/nix/store/9hyjjdx8swcs87j75x86fiqakswnvsam-python3-3.11.10-env/lib/python3.11/site-packages/pygmt/clib/session.py", line 624, in call_module
    raise GMTCLibError(
pygmt.exceptions.GMTCLibError: Module 'psconvert' failed with status code 79:
psconvert [ERROR]: System call [gs -q -dNOSAFER -dNOPAUSE -dBATCH -sDEVICE=bbox -DPSL_no_pagefill -dMaxBitmap=2147483647 -dUseFastColor=true '~/.gmt/sessions/gmt_session.680420/gmt_1.ps-' 2> '~/.gmt/sessions/gmt_session.680420/psconvert_680420c.bb'] returned error 256.
```

### System information

```bash
PyGMT information:
  version: v0.11.0
System information:
  python: 3.11.10 (main, Sep  7 2024, 01:03:31) [GCC 13.2.0]
  executable: /nix/store/9hyjjdx8swcs87j75x86fiqakswnvsam-python3-3.11.10-env/bin/python3.11
  machine: Linux-6.6.63-x86_64-with-glibc2.39
Dependency information:
  numpy: 1.26.4
  pandas: 2.2.1
  xarray: 2024.2.0
  netCDF4: 1.6.5
  packaging: 24.0
  contextily: None
  geopandas: None
  ipython: None
  rioxarray: None
  ghostscript: 10.04.0
GMT library information:
  binary version: 6.4.0
  cores: 8
  grid layout: rows
  image layout: 
  library path: /nix/store/kqdqszdw10sk2wdy9sk1zci1zn3hc31h-gmt-6.4.0/lib/libgmt.so
  padding: 2
  plugin dir: /nix/store/kqdqszdw10sk2wdy9sk1zci1zn3hc31h-gmt-6.4.0/lib/gmt/plugins
  share dir: /nix/store/kqdqszdw10sk2wdy9sk1zci1zn3hc31h-gmt-6.4.0/share/gmt
  version: 6.4.0
```

**Comment by seisman** [comment]
Could you please share your `example_data.txt` file so that we can reproduce the example?

**Comment by seisman** [comment]
The documentation says:

> log ([bool](https://docs.python.org/3/library/functions.html#bool)) – For logarithmic interpolation scheme with input given as logarithms. Expects input z-values provided via series to be log10(z), assigns colors, and writes out z.

So, in your case, you should use something lik e`series=[0, 4]`.

**Comment by yvonnefroehlich** [comment]
BTW, maybe you want to consider updating to PyGMT v0.13.0 🙂. After this you do not need to wrap labels containing white spaces with extra quotation marks.

**Comment by paradx** [comment]
Thanks for the quick relpy.

@yvonnefroehlich updated my os today and that bumped pygmt to v.0.13.0. :+1:
